// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/addNote": {
    params: {};
  };
  "/delNote": {
    params: {};
  };
  "/test": {
    params: {};
  };
  "/note/:noteDetail": {
    params: {
      "noteDetail": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/addNote" | "/delNote" | "/test" | "/note/:noteDetail";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/addNote.jsx": {
    id: "routes/addNote";
    page: "/addNote";
  };
  "routes/delNote.jsx": {
    id: "routes/delNote";
    page: "/delNote";
  };
  "routes/test.jsx": {
    id: "routes/test";
    page: "/test";
  };
  "routes/noteDetail.jsx": {
    id: "routes/noteDetail";
    page: "/note/:noteDetail";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/home": typeof import("./app/routes/home.jsx");
  "routes/addNote": typeof import("./app/routes/addNote.jsx");
  "routes/delNote": typeof import("./app/routes/delNote.jsx");
  "routes/test": typeof import("./app/routes/test.jsx");
  "routes/noteDetail": typeof import("./app/routes/noteDetail.jsx");
};